version: '3.8'

services:
  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://cleidoscope:root@db:5432/tasks
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=cleidoscope
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=tasks
      - POSTGRES_HOST=localhost

volumes:
  postgres_data: