import { rem } from '@mantine/core';

export const theme: any = {
  colorScheme: 'light',
  focusRing: 'auto',
  cursorType: 'pointer',
  defaultRadius: 5,
  dir: 'ltr',
  colors: {
    red: [
      '#FFECF0',
      '#FFCCD8',
      '#FFACC0',
      '#FF8DA8',
      '#FD6A8D',
      '#F84D76',
      '#F32C5B',
      '#E91547',
      '#CA0835',
      '#D00000',
    ],
    blue: [
      '#E3E8F2',
      '#D4DFEF',
      '#B3C4DF',
      '#96AACC',
      '#7991BB',
      '#5F79A7',
      '#455F8F',
      '#2A4473',
      '#1D315D',
      '#0F1F3D',
    ],
    offWhite: [
      '#F0F0F0',
      '#E4E4E4',
      '#D9D9D9',
      '#C7C7C7',
      '#B1B1B1',
      '#8E8E8E',
      '#666666',
      '#3A3A3B',
      '#303031',
      '#252526',
    ],
    gold: [
      '#FFFAEE',
      '#FFF5DB',
      '#FFEFC2',
      '#FFE7A4',
      '#FCDB7E',
      '#F5CE61',
      '#ECBE40',
      '#DBBE46',
      '#E4C441',
      '#DEBE3f',
    ],
    green: [
      '#F3FFF5',
      '#EAFFEC',
      '#DBFBDF',
      '#C7F7CC',
      '#A8EAAF',
      '#8AD692',
      '#70BF78',
      '#5CB265',
      '#3FA24A',
      '#268731',
    ],
    dark: [
      '#1b1b1e1a',
      '#1b1b1e33',
      '#1b1b1e4d',
      '#1b1b1e66',
      '#1b1b1e80',
      '#1b1b1e99',
      '#1b1b1eb3',
      '#1b1b1ecc',
      '#1b1b1ee6',
      '#1B1B1E',
    ],
    gray: [
      '#E0E0E0',
      '#D2D2D2',
      '#ADADAD',
      '#F7F7F7',
      '#D9D9D9',
      '#808080',
      '#757575',
      '',
      '',
      '',
    ],
    white: [
      '#FFFFFF',
      '#FAF6E7',
      '#F3F3F3',
      '#F6F1E9',
      '#F2F2f2',
      '',
      '',
      '',
      '',
      '',
    ],
    brown: [
      '#CDAC82',
      '#9D733F',
      '#5A4730',
      '#9D733F',
      '#9D733F',
      '#9D733F',
      '#9D733F',
      '#9D733F',
      '#9D733F',
      '#9D733F',
    ],
    black: ['#000000', '#2A2A2A', '', '', '', '', '', '', '', ''],
    pink: ['#BF6E6E', '', '', '', '', '', '', '', '', ''],
    grape: ['#83BF6E', '', '', '', '', '', '', '', '', ''],
    violet: ['', '', '', '', '', '', '', '', '', ''],
    indigo: ['', '', '', '', '', '', '', '', '', ''],
    cyan: ['', '', '', '', '', '', '', '', '', ''],
    // yellow: ["", "", "", "", "", "", "#f59f00", "", "#f59f00", ""],
    lime: ['#00D084', '#7BDCB5', '', '', '', '', '', '', '', ''],
    teal: ['', '', '', '', '', '', '', '', '', ''],
    orange: ['', '', '', '', '', '', '', '', '', ''],
  },
  primaryColor: 'red',
  primaryShade: {
    light: 7,
    dark: 9,
  },

  fontFamily: 'Inter, sans-serif',
  fontSizes: {
    xs: '12px',
    sm: '14px',
    md: '16px',
    lg: '18px',
    xl: '20px',
  },

  shadows: {
    xs: '1px 1px 3px rgba(0, 0, 0, .25)',
    sm: '1px 1px 3px rgba(0, 0, 0, .25)',
    md: '1px 1px 3px rgba(0, 0, 0, .25)',
    lg: '4px 4px 18px rgba(29, 49, 93, 0.05)',
    xl: '4px 4px 18px rgba(29, 49, 93, 0.05)',
    default: '0 0 0 2px rgba(0, 0, 0, 0.1)',
  },

  headings: {
    fontFamily: 'Poppins, sans-serif',
    fontWeight: 700,
    sizes: {
      h1: {
        fontSize: '70px',
        fontWeight: 700,
        lineHeight: '80px',
      },
      h2: {
        fontSize: '50px',
        fontWeight: 700,
        lineHeight: '68px',
      },
      h3: {
        fontSize: '42px',
        fontWeight: 700,
        lineHeight: '58px',
      },
      h4: {
        fontSize: '36px',
        fontWeight: 700,
        lineHeight: '52px',
      },
      h5: {
        fontSize: '26px',
        fontWeight: 700,
        lineHeight: '42px',
      },
      h6: {
        fontSize: '22px',
        fontWeight: 700,
        lineHeight: '32px',
      },
    },
  },

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  globalStyles: (theme: any) => ({
    body: {
      ...theme?.fn?.fontStyles(),
      backgroundColor:
        theme.colorScheme === 'dark' ? theme.colors.dark[7] : '#faf6e7',
    },
    '.common-upload-button': {
      backgroundColor: theme.colors.gray[3],
      color: theme.colors.dark[1],
      border: `${rem(1)} solid ${theme.colors.gray[0]}`,
      fontWeight: 600,
      fontSize: rem(12),
      padding: `${rem(7)} ${rem(12)}`,
      '& svg': {
        marginRight: '6px',
      },
      '&:hover': {
        backgroundColor: theme.colors.gray[3],
        color: theme.colors.dark[1],
      },
    },
    '.common-table': {
      '& thead th': {
        color: theme.colors.gray[2],
      },
    },
    '.button-shadow': {
      boxShadow: '4px 4px 18px rgba(29, 49, 93, 0.05)',
    },
    '.filter-shadow': {
      filter: 'drop-shadow(4px 4px 24px rgba(0, 0, 0, 0.05))',
    },
    '.active-border': {
      boxShadow: `inset 3px 0px 0px 0px ${theme.colors.red[7]}`,
      backgroundColor: '#fff',
    },
    '.reverse-progress': {
      transform: 'rotate(180deg)',
    },
  }),
};
